name: Nightly Tests
on:
  schedule:
    - cron: '0 10 * * *' # run at 10:00:00 UTC
  workflow_dispatch:  # manual trigger

jobs:
  doctest:
    uses: ./.github/workflows/doctest.yaml
  format:
    uses: ./.github/workflows/format.yaml
  test:
    uses: ./.github/workflows/test.yaml
  test-deps:
    uses: ./.github/workflows/test-deps.yaml
